# Generated by Django 4.1.2 on 2022-10-11 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recitales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recital',
            options={'verbose_name': 'Recital', 'verbose_name_plural': 'Recitales'},
        ),
        migrations.AddField(
            model_name='recital',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 18, 14, 13, 981152, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recital',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30, verbose_name='Alumno(a)')),
                ('piece', models.CharField(max_length=60, verbose_name='Pieza')),
                ('composer', models.CharField(max_length=30, verbose_name='Compositor')),
                ('teacher', models.CharField(max_length=30, verbose_name='Maestro')),
                ('recital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recitales.recital')),
            ],
            options={
                'verbose_name': 'Participacion',
                'verbose_name_plural': 'Participaciones',
            },
        ),
    ]
