# Generated by Django 4.1.2 on 2022-10-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recitales', '0002_alter_recital_options_alter_recital_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacion',
            options={'verbose_name': 'Participacion', 'verbose_name_plural': 'Participaciones'},
        ),
    ]
